services:
  web:
    build: .
    image: random_bot:latest
    command: uvicorn app.web.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    restart: unless-stopped

  bot:
    image: random_bot:latest
    depends_on:
      - web
    command: python -m app.bot.main
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /root/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    restart: unless-stopped

volumes:
  app_data: 